# Generated by Django 4.2.4 on 2023-10-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="storageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("VALUE_EUR", models.DecimalField(decimal_places=5, max_digits=10)),
                (
                    "RELEASE_CLAUSE_EUR",
                    models.DecimalField(decimal_places=5, max_digits=10),
                ),
                ("AGE", models.IntegerField()),
                ("POTENTIAL", models.DecimalField(decimal_places=5, max_digits=10)),
                (
                    "MOVEMENT_REACTION",
                    models.DecimalField(decimal_places=5, max_digits=10),
                ),
            ],
        ),
    ]
