# Generated by Django 4.2.4 on 2023-10-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_storagemodel_confidence_storagemodel_prediction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storagemodel",
            name="AGE",
            field=models.IntegerField(default=0, verbose_name="AGE"),
        ),
        migrations.AlterField(
            model_name="storagemodel",
            name="MOVEMENT_REACTION",
            field=models.FloatField(default=0, verbose_name="MOVEMENT REACTION"),
        ),
        migrations.AlterField(
            model_name="storagemodel",
            name="POTENTIAL",
            field=models.FloatField(default=0, verbose_name="POTENTIAL"),
        ),
        migrations.AlterField(
            model_name="storagemodel",
            name="RELEASE_CLAUSE_EUR",
            field=models.FloatField(default=0, verbose_name="RELEASE CLAUSE EUR"),
        ),
        migrations.AlterField(
            model_name="storagemodel",
            name="VALUE_EUR",
            field=models.FloatField(default=0, verbose_name="VALUE EUR"),
        ),
    ]
